dist: xenial

services:
  - postgresql
addons:
  postgresql: "9.6"

before_script:
 - psql -c "create user decide with password 'decide'" 
 - psql -c "create database decide owner decide"
 - psql -U postgres -c "ALTER USER decide CREATEDB"

language: python 
python: 
- "3.6"
install: 
- pip install -r requirements.txt
script: 
- cd decide
- cp local_settings.travis.py local_settings.py
- python ./manage.py test store

