dist: xenial

services:
  - postgresql
addons:
  postgresql: "9.6"

before_script:
 - psql -c "create user decide with password 'decide'" 
 - psql -c "create database decide owner decide"
 - psql -U postgres -c "ALTER USER decide CREATEDB"


language: python 
python: 
- "3.6"
env: 
- DJANGO=2.0 DB=postgres
install: 
- pip install -r requirements.txt
script: 
- python manage.py test store --keepdb --with-xunit

